### ISSUE TITLE
Insert arbitrary string as type

### ISSUE THREAD

**Issue by dt-rush** [dave/jennifer#36]
If I've read my types in as strings, for example I have a string which is `"[2]uint16"`, how can I insert that into a statement? `Id()` isn't working, causing formatting errors to panic

**Comment by dave** [comment]
Jennifer doesn't really support emitting arbitrary strings into the output, but you can probably use `Op` to do that... Here's a demo: https://play.jsgo.io/028c3c15e35610afc73e684c964201bc84bb0263

```go
package main

import (
	"fmt"

	"github.com/dave/jennifer/jen"
)

func main() {
	myType := "[2]uint16"
	f := jen.NewFile("foo")
	f.Var().Id("bar").Op(myType)
	fmt.Printf("%#v", f)
}
```

Output:
```go
package foo

var bar [2]uint16
```

Is that what you're trying to do?

**Comment by dt-rush** [comment]
Thanks for the quick reply, wow!

I ended up using `Id()`, and actually I've used it in two places:

```
arbitraryTypeStr := "sdl.Rect"
Func().Id("functionA").Params(Id("x").Int()).
    Params(Id(arbitraryTypeStr), Error()).
    Block(
        Return(
            Id(arbitraryTypeStr).Values(),
            Nil(),
        ),
    )
```

Produces:

```
func functionA (x int) (sdl.Rect, error) {
    return sdl.Rect{}, nil
}
```

**Comment by dave** [comment]
Jennifer doesn't really have much knowledge of what you're inserting... It's pretty dumb really... The logic is mostly concerned with getting groupings correct - e.g. brackets and separators. 

Things like `Id` and `Op` are really just inserting strings into the output. See the [token render function](https://github.com/dave/jennifer/blob/9be926694b0df8a097bb0b1e7386e3ce410d7cd3/jen/tokens.go#L38-L100) for the exact implementation details... so I don't really know if there's any enhancement needed. 

For readability you might want a separate method to add an arbitrary string, but since it's not really an intended use case, I'm hesitant.

**Comment by dave** [comment]
> Great repo btw!!!

Glad it's of use!

**Comment by dt-rush** [comment]
Yeah, I suppose you're right in that, were it a type I'd defined, like "MyDataType", I'd put it in those places via `Id("MyDataType")` anyhow. I'd say this can be closed, now that anyone in future can find this issue in the issues archive through some keywords if they face the same situation.

**Comment by dave** [comment]
Thanks!
