### ISSUE TITLE
Feature Request: Do not render [] if .Types() is called with no arguments

### ISSUE THREAD

**Issue by IsSkyfalls** [dave/jennifer#93]
Hello!
I was trying to generate similar functions that accept 0 to n arguments with different generic types. [problematic code](https://github.com/IsSkyfalls/go-retry-generics/blob/master/codegen.go#L146)

The current implementation of .Type() renders a pair of empty brackets when no arguments are provided, which is invalid code.  I could wrap every .Type() call in a .Do() with checks, but it would be so much easier to fix it in this project.

Fix 1:
Add a check to [render.go](https://github.com/dave/jennifer/blob/master/genjen/render.go#L67) for the name "Types" and generate a check for len(args)==0

Fix 2:
Add a new field to the [groups struct](https://github.com/dave/jennifer/blob/master/genjen/data.go#L7), then check for that flag and generate the same code. This might be good for extensibility, but as for now, [] when used for type constraints is the only type of brackets that cannot be empty.

I can do a pr, but I think it's better for you to decide which option is better.

**Comment by dave** [comment]
Yes you're right. Since empty types braces is always invalid code, we should omit them if `Types()` is empty. It was a little more complex than you thought because `Null()` items should be treated as such. I've fixed this and tagged as v1.5.1. Here's the fix: https://github.com/dave/jennifer/commit/2cd7ed762bb206d288c68a9286b3034f5e61f8e4
